const fs = require("fs");
const path = require("path");
const archiver = require("archiver");

const STYLE_CSS = {
  flat: "flat.css", basic: "basic.css", gradient: "gradient.css",
  volume: "volume.css",
};
const READY_STYLES = new Set(["flat"]);

const COMMON_FILES = [
  "css/tokens.css",
  "js/tokens.js",
  "js/palette_tools.js",
  "js/palettes.js",
  "js/i18n.js",
];
const FLAT_CONTROLS = [
  "js/controls/flat.js",
  "js/controls/rotary-knob.js",
  "js/controls/gauges.js",
];

function _generateStyleReadme(style, fileList) {
  const cap = style.charAt(0).toUpperCase() + style.slice(1);
  return `# Web App Controls — ${cap} Style

## Exported files

${fileList.map((f) => "- `" + f + "`").join("\n")}

## Quick start

1. Copy all exported files into your project, keeping the directory structure.

2. In your HTML \`<head>\`, load the CSS files:

\`\`\`html
<link rel="stylesheet" href="css/tokens.css" />
<link rel="stylesheet" href="css/styles/${STYLE_CSS[style]}" />
\`\`\`

3. At the bottom of \`<body>\` (or as ES modules), load the JS:

\`\`\`html
<script type="module" src="js/controls/${style}.js"></script>
<script type="module" src="js/controls/rotary-knob.js"></script>
<script type="module" src="js/controls/gauges.js"></script>
\`\`\`

4. Use the custom elements in your HTML:

\`\`\`html
<push-button label="Click me"></push-button>
<toggle-switch label="WiFi"></toggle-switch>
<segmented-control values='["A","B","C"]' value="A" columns="3"></segmented-control>
<rotary-knob mode="continuous" min="0" max="100" value="50" label="Volume" flat></rotary-knob>
<circular-gauge value="60" min="0" max="100" label="Speed"></circular-gauge>
<linear-gauge value="45" min="0" max="100" direction="horizontal" label="Level"></linear-gauge>
<bar-chart title="Revenue" data="[[40,60,80,50]]" labels='["Q1","Q2","Q3","Q4"]'></bar-chart>
<line-chart title="Trend" data="[[10,30,20,50,40]]" labels='["A","B","C","D","E"]'></line-chart>
<date-calendar value="2025-01-15"></date-calendar>
\`\`\`

---

*Generated by webappcontrols export — ${new Date().toISOString().split("T")[0]}*
`;
}

module.exports = (req, res) => {
  const style = (req.query.style || "flat").toLowerCase();
  if (!READY_STYLES.has(style)) {
    return res.status(400).json({ ok: false, error: `Style "${style}" is not yet available for export.` });
  }

  const pub = path.join(process.cwd(), "public");
  const cssFile = `css/styles/${STYLE_CSS[style]}`;
  const files = [...COMMON_FILES, cssFile, ...FLAT_CONTROLS];

  // Add i18n JSON files
  const i18nDir = path.join(pub, "i18n");
  let i18nFiles = [];
  try {
    i18nFiles = fs.readdirSync(i18nDir)
      .filter((f) => f.endsWith(".json"))
      .map((f) => `i18n/${f}`);
  } catch { /* ignore */ }

  const allFiles = [...files, ...i18nFiles];

  res.setHeader("Content-Type", "application/zip");
  res.setHeader("Content-Disposition", `attachment; filename="webappcontrols-${style}.zip"`);

  const archive = archiver("zip", { zlib: { level: 9 } });
  archive.on("error", (err) => res.status(500).send({ error: err.message }));
  archive.pipe(res);

  for (const relPath of allFiles) {
    const absPath = path.join(pub, relPath);
    if (fs.existsSync(absPath)) {
      archive.file(absPath, { name: relPath });
    }
  }

  const readme = _generateStyleReadme(style, allFiles);
  archive.append(readme, { name: "STYLE_README.md" });

  archive.finalize();
};
